services:
  frontend:
    container_name: frontend
    image: rahul38/task-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

networks:
  app-network:
    external: true
