services:
  backend:
    container_name: backend
    image: rahul38/task-backend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always
    env_file:
      - .env

networks:
  app-network:
    external: true
