name: Deploy Auth App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t rahul38/auth-app:latest .
          docker push rahul38/auth-app:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/rahul/auth-app
            docker-compose down
            docker pull rahul38/auth-app:latest
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > /home/rahul/auth-app/.env
            echo "PORT=3000" > /home/rahul/auth-app/.env
            docker-compose up -d
