name: Deploy to Azure VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t rahul38/task-backend:latest ./backend
          docker push rahul38/task-backend:latest
          docker build -t rahul38/tast-fronted:latest ./frontend
          docker push rahul38/tast-fronted:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            PROJECT_DIR="home/rahul/task-app"

            rm -rf $PROJECT_DIR
            git clone -b main https://github.com/rahul-suthar/Auth.git $PROJECT_DIR

            cat <<EOF | tee $PROJECT_DIR/backend/.env
            MONGO_URI=${{ secrets.MONGO_URI }}
            PORT=3000
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF

            cat <<EOF | tee $PROJECT_DIR/frontend/.env
            REACT_APP_API_URL=http://${{ secrets.SERVER_IP }}/api
            EOF

            cd $PROJECT_DIR/backend
            docker-compose down
            docker pull rahul38/auth-backend:latest
            docker-compose up -d

            cd $PROJECT-DIR/frontend
            docker-compose down
            docker pull rahul38/auth-frontend:latest
            docker-compose up -d

            docker image prune -af
